import type { IconType } from "react-icons";
import { FaGoogle } from "react-icons/fa";
import {
  LuApple,
  LuArrowLeft,
  LuBath,
  LuBedDouble,
  LuBuilding2,
  LuCamera,
  LuCar,
  LuCheck,
  LuChevronLeft,
  LuChevronRight,
  LuCircleAlert,
  LuCloudUpload,
  LuCreditCard,
  LuDroplets,
  LuFileText,
  LuFilter,
  LuFlower2,
  LuHeart,
  LuHouse,
  LuImage,
  LuKeyRound,
  LuLandmark,
  LuLaptop,
  LuLock,
  LuMapPin,
  LuMenu,
  LuPaperclip,
  LuPlay,
  LuQrCode,
  LuSend,
  LuShare2,
  LuShowerHead,
  LuSlidersHorizontal,
  LuSmartphone,
  LuSnowflake,
  LuSparkles,
  LuStar,
  LuTrees,
  LuTriangleAlert,
  LuTv,
  LuUser,
  LuUtensilsCrossed,
  LuWashingMachine,
  LuWifi,
  LuX,
} from "react-icons/lu";

export const Icons = {
  Heart: LuHeart,
  User: LuUser,
  Menu: LuMenu,
  Close: LuX,
  Paperclip: LuPaperclip,
  Check: LuCheck,
  Star: LuStar,
  ChevronLeft: LuChevronLeft,
  ChevronRight: LuChevronRight,
  ArrowLeft: LuArrowLeft,
  House: LuHouse,
  Key: LuKeyRound,
  Car: LuCar,
  Wifi: LuWifi,
  Kitchen: LuUtensilsCrossed,
  Tv: LuTv,
  Laptop: LuLaptop,
  Flower: LuFlower2,
  Snowflake: LuSnowflake,
  Droplets: LuDroplets,
  WashingMachine: LuWashingMachine,
  Trees: LuTrees,
  Building: LuBuilding2,
  Camera: LuCamera,
  Bed: LuBedDouble,
  Play: LuPlay,
  MapPin: LuMapPin,
  Sparkles: LuSparkles,
  CreditCard: LuCreditCard,
  Smartphone: LuSmartphone,
  Landmark: LuLandmark,
  QrCode: LuQrCode,
  CloudUpload: LuCloudUpload,
  Warning: LuTriangleAlert,
  Alert: LuCircleAlert,
  Share: LuShare2,
  Send: LuSend,
  Filter: LuFilter,
  Sliders: LuSlidersHorizontal,
  FileText: LuFileText,
  Image: LuImage,
  Lock: LuLock,
  Bath: LuBath,
  Shower: LuShowerHead,
  Google: FaGoogle,
  Apple: LuApple,
} as const;

export type AppIcon = (typeof Icons)[keyof typeof Icons];

export const amenityIcons: Record<string, IconType> = {
  "Wi-Fi": Icons.Wifi,
  Kitchen: Icons.Kitchen,
  Parking: Icons.Car,
  TV: Icons.Tv,
  Workspace: Icons.Laptop,
  Balcony: Icons.Flower,
  "Air conditioning": Icons.Snowflake,
  "Hot water": Icons.Shower,
  "Self check-in": Icons.Key,
  "Washing machine": Icons.WashingMachine,
  Garden: Icons.Trees,
  "Rooftop terrace": Icons.Building,
};

export const placeholderIcons = {
  hero: Icons.House,
  property: Icons.House,
  gallery: Icons.Camera,
  "gallery-sm": Icons.Camera,
  bedroom: Icons.Bed,
  bathroom: Icons.Bath,
  lifestyle: Icons.Sparkles,
  video: Icons.Play,
  avatar: Icons.User,
  map: Icons.MapPin,
} as const;
